### ISSUE TITLE
Compilation of dynd python fails on master

### ISSUE THREAD

**Issue by cpcloud** [libdynd/dynd-python#293]
Looks like API changes are the culprit:

```sh
In file included from /Users/pcloud/code/py/dynd-python/dynd/src/array_as_numpy.cpp:17:
/Users/pcloud/code/py/dynd-python/dynd/include/copy_to_numpy_arrfunc.hpp:41:41: error: unknown template name 'declfunc'
extern struct copy_to_numpy : dynd::nd::declfunc<copy_to_numpy> {
                                        ^
/Users/pcloud/code/py/dynd-python/dynd/include/copy_to_numpy_arrfunc.hpp:42:10: error: no type named 'callable' in namespace
      'dynd::nd'; did you mean 'dynd::gfunc::callable'?
  static dynd::nd::callable make();
         ^~~~~~~~~~~~~~~~~~
         dynd::gfunc::callable
/Users/pcloud/miniconda/envs/py27/include/dynd/func/callable.hpp:26:7: note: 'dynd::gfunc::callable' declared here
class callable {
      ^
6 warnings and 2 errors generated.
make[2]: *** [CMakeFiles/pydynd.dir/dynd/src/array_as_numpy.cpp.o] Error 1
make[1]: *** [CMakeFiles/pydynd.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by cpcloud** [comment]
libdynd compiles fine

**Comment by izaid** [comment]
Yep, there are major API changes! Sorry, this will be the case for the next little while -- it's all fine with master of libdynd, right?

**Comment by cpcloud** [comment]
Is there a version of dynd Python that works with libdynd master

**Comment by izaid** [comment]
Okay, sorry, that was my question. The current libdynd master should work with dynd-python master. Are you saying it doesn't for you?

**Comment by cpcloud** [comment]
Yes dynd Python doesn't compile on master while libdynd master does compile.

**Comment by izaid** [comment]
I think this is only caused by having the old headers present as well. Can you delete "/Users/pcloud/miniconda/envs/py27/include/dynd". I think it should work then.

**Comment by cpcloud** [comment]
[pebkac](https://en.wikipedia.org/wiki/User_error#PEBKAC) error
