### ISSUE TITLE
tests with older numpies on travis

### ISSUE THREAD

**Issue by jreback** [libdynd/dynd-python#341]

**Comment by insertinterestingnamehere** [comment]
This is fairly easy to do. The real question is how far back we want to support. Thoughts?

**Comment by jreback** [comment]
I think if you support >= 1.7.0 would be gr8. < 1.7 is a nightmare :<

**Comment by insertinterestingnamehere** [comment]
That sounds fine with me. We usually require that our packages be fairly recent, but the few numpy features we use are relatively stable. I just opened a PR with the tentative changes. @mwiebe @izaid any thoughts on which numpy versions we want to support? 1.7 works fine right now.
