### ISSUE TITLE
COMPAT: boolean of a dtype

### ISSUE THREAD

**Issue by jreback** [libdynd/dynd-python#353]
I find this odd.

```
In [1]: bool(np.dtype('int64'))
Out[1]: False

In [2]: bool(ndt.type('int64'))
Out[2]: True
```

**Comment by izaid** [comment]
This is odd, but it seems like NumPy is the offender here. Any thoughts?

**Comment by jreback** [comment]
I agree its prob numpy that is the culprit.

cc @njsmith

**Comment by njsmith** [comment]
Huh, I have no idea what is up with that. (And now I'm looking suspiciously at @jreback for noticing.) File a bug on numpy?

**Comment by jreback** [comment]
haha, I had some code with was doing:

```
name = getattr(dtype,'name',None)
if name:
   ....
```

which worked in DyND and not in numpy ....purely accidental.

**Comment by jreback** [comment]
reported to numpy, this is correct in DyND
