### ISSUE TITLE
Suspected fatal error: CMake Error: Internal CMake error, TryCompile configure of cmake failed

### ISSUE THREAD

**Issue by michaelpacer** [libdynd/dynd-python#370]
I'm getting a strange error, I really hope it does not arise because I cloned into a directory that was not my home directory (`~`). If the install instructions rely on the user installing from source to work, I oppose it strongly. 

When installing from source, there is no explanation of how to install CMake such that it will compile correctly on at least my instance `OSX 10.10.5`. Once I figure out how to get this to work, I'll push some kind of `install_osx` doc. 

What I tried was just 

    brew install cmake

which seemed to work.

But then when I ran cmake on libdynd

Here's a rundown of the full error log: 

        CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but the matching SDK does not exist
  at:"/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk"

        Instead using SDK: "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk".

    Call Stack (most recent call first):
        /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
        CMakeLists.txt:3 (project)
    CMake Error at /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
        CMAKE_OSX_DEPLOYMENT_TARGET is '10.9' but CMAKE_OSX_SYSROOT:
        ""
        is not set to a MacOSX SDK with a recognized version.  Either set
        CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
        empty.
    Call Stack (most recent call first):
        /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
        CMakeLists.txt:3 (project)
    CMake Error: Internal CMake error, TryCompile configure of cmake failed

I'm going to figure this out and will post updates as I do.

**Comment by michaelpacer** [comment]
This is the documentation for CMAKE_OSX_DEPLOYMENT_TARGET:

> Specify the minimum version of OS X on which the target binaries are to be deployed. CMake uses this value for the -mmacosx-version-min flag and to help choose the default SDK (see CMAKE_OSX_SYSROOT).

> If not set explicitly the value is initialized by the MACOSX_DEPLOYMENT_TARGET environment variable, if set, and otherwise computed based on the host platform.

> The value of this variable should be set prior to the first project() or enable_language() command invocation because it may influence configuration of the toolchain and flags. It is intended to be set locally by the user creating a build tree.

> This variable is ignored on platforms other than OS X.

This does not actually tell you how to set the value. It does not link to where you go to set the value. I gather that it's with an `=` sign and then some symbols (or possibly no symbols) but that is by example to the `-CMAKE_BUILD_TYPE=Release` alternate flag. However, it is not at all clear how to set it to an empty value, since there was no syntax, and so I do not yes know how to convey an empty anything let alone set something to `empty`, unless they mean write the string empty, which is completely ambiguous and could just be given as an example on the rest of that line, which is an orphan anyway, so there's space for an example.

**Comment by michaelpacer** [comment]
Ok none of these work: 

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
cmake -DCMAKE_BUILD_TYPE=Debug ..
cmake -DCMAKE_BUILD_TYPE=Release ..
cmake -D -CMAKE_BUILD_TYPE=Release -CMAKE_OSX_DEPLOYMENT_TARGET="" ..
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_DEPLOYMENT_TARGET="" ..
```

And 
```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_DEPLOYMENT_TARGET=empty ..
``` 
left the traceback:
```
CMake Warning at /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/Platform/Darwin-Initialize.cmake:97 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is 'empty' but the matching SDK does not exist
  at:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSXempty.sdk"

  Instead using SDK:

   "/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk".
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInitialize.cmake:18 (include)
  CMakeLists.txt:7 (project)


CMake Error at /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is 'empty' but CMAKE_OSX_SYSROOT:

   ""

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:7 (project)

**Comment by michaelpacer** [comment]
Apparently 

```
cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_OSX_SYSROOT=10.10.5 ..
CMake Error at /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/Platform/Darwin.cmake:76 (message):
  CMAKE_OSX_DEPLOYMENT_TARGET is 'empty' but CMAKE_OSX_SYSROOT:

   "10.10.5"

  is not set to a MacOSX SDK with a recognized version.  Either set
  CMAKE_OSX_SYSROOT to a valid SDK or set CMAKE_OSX_DEPLOYMENT_TARGET to
  empty.
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.3.0/share/cmake/Modules/CMakeSystemSpecificInformation.cmake:36 (include)
  CMakeLists.txt:7 (project)


-- Configuring incomplete, errors occurred!
```

doesn't work either.

**Comment by michaelpacer** [comment]
This looks fruitful: http://cmake.org/Wiki/CMake_FAQ#Why_does_CMake_not_find_my_Xcode_compiler_on_OS_X_with_the_Unix_Makefiles_generator.3F

**Comment by michaelpacer** [comment]
Hmm looking at the `conda.recipe/build.sh` I see that these options are commented out

```
#elif [ `uname` == Darwin ]; then
 #   export CC="$PREFIX/bin/gcc"
  #  export CXX="$PREFIX/bin/g++"
#    CPPFLAGS="-stdlib=libc++"
  #  EXTRAOPTIONS="-DCMAKE_OSX_DEPLOYMENT_TARGET=10.9"
   # MACOSX_DEPLOYMENT_TARGET=10.9
```
and when I tried to run this in my iterm2 split pane,

```
cmake \
    $EXTRAOPTIONS \
    -DDYND_INSTALL_LIB=ON \
    -DDYND_BUILD_BENCHMARKS=OFF \
    -DCMAKE_INSTALL_PREFIX=$PREFIX .. || exit 1
```

the iterm2 terminal emulator disappeared, and messed up my pane structure (leaving me with two really tall panes to the right side, which is not at all what I want. I kinda guessed that that command wasn't going to work but I didn't think it would crash the terminal. 

Anyway, now I'm actually calling it a night.

**Comment by izaid** [comment]
Hey @michaelpacer! First, thanks for giving it a try -- sorry that it was a bit frustrating. Let's try and sort this out.

First, OS X *should* work fine to my knowledge. I'm going to cc @cpcloud on this, because I know he was compiling dynd-python on OS X as recently as last week.

Second, you can just use the dev channel if you want to avoid all of this: "conda install dynd-python -c dynd/channel/dev".

Back to your issue. What version of XCode do you have? What does "xcodebuild -version -sdk" give you?

**Comment by insertinterestingnamehere** [comment]
I ran across this recently when building on OSX 10.10. The build recipe I figured out for libdynd was this:

    cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_BUILD_TYPE=Release ..

Oddly enough, for the Python bindings, I didn't need any unusual setup steps. The temporary directory created for building the files incorrectly identified the OS as OSX 10.5, but the build ran fine anyway.

**Comment by cpcloud** [comment]
echoing @insertinterestingnamehere, here's how i compile libdynd then dynd-python from source:

i'm using conda, which is excellent when compiling and installing a shared library from source as it doesn't require sudo and therefore won't install things into weird places. That's what the `CMAKE_INSTALL_PREFIX` variable is for.

```sh
alias nproc='sysctl -n hw.ncpu'
source activate dynd
cd /path/to/libdynd
mkdir build
cd build
cmake .. -DCMAKE_OSX_DEPLOYMENT_TARGET=10.10 -DCMAKE_INSTALL_PREFIX=~/miniconda3/envs/dynd
make -j `nproc`  # parallel build
make install
cd /path/to/dynd-python
python setup.py install
export LD_LIBRARY_PATH=~/miniconda3/envs/dynd/lib:${LD_LIBRARY_PATH}
cd
python -c 'from dynd import nd; print(nd.array("success!"))'
```

**Comment by michaelpacer** [comment]
@insertinterestingnamehere Modifying yours to `cmake -DCMAKE_OSX_DEPLOYMENT_TARGET=10.11 -DCMAKE_BUILD_TYPE=Release ..` to fit my OSX SDK worked(or at least the `cmake` step did). Huzzah!

@izaid No problem! Not that frustrating — about what I expected I just try to be verbose about the paths that I've tried so that other people who run into these kinds of issues in the future will have a variety of search terms that will result in them finding the solution. A sort of "Issues as future docs" approach.
 
The relevant version info. 
```
$ xcodebuild -version -sdk
MacOSX10.11.sdk - OS X 10.11 (macosx10.11)
SDKVersion: 10.11
Path: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk
```

@izaid @cpcloud Thank you for the `conda`/`miniconda` based suggestions, but I don't think that they'll work super well for me right now. So I've not actually set up `conda` on my system (I've been rolling my own scientific python stack for a while with `pip` and `brew` and changing everything a few months before I finish my dissertation is not on the table right now), so would those solutions work without `conda`/`miniconda` being preëstablished in my setup? I ask because I'm guessing they wouldn't, and the `BUILD_INSTALL.md` seems to be explicitly written for those who aren't using `conda` already, so neither of those solution work as ways to modify that install doc. 

If nothing is special about `miniconda3` (i.e., it's just your usual `virtualenv` top level directory) then could instead we could add the line `mkdir -p ~/miniconda3/envs/dynd` and this would still work without having installed `miniconda`? 

@cpcloud You're right I should have installed it in a `virtualenv` fortunately nothing else has seemed to break…that said I haven't tried too much since doing that. Hopefully I didn't screw myself over. 

Also, what is `alias nproc='sysctl -n hw.ncpu'` doing such that it creates a parallel build? (Sidenote: I didn't know the `\`var\`` name could be used instead of `$var`; thank you for bash lesson!)

**Comment by cpcloud** [comment]
@michaelpacer the `alias` makes a command that returns the number of CPUs ... most unixes call this nproc, OS X decided to be the awkward turtle in the room

**Comment by michaelpacer** [comment]
Ok `libdynd` worked all the way through, and then in `dynd-python` the `sudo make install` command failed. 

could it be because I'm working in a virtualenv?

```…/dynd-python/build (git: master)
$ sudo make install
make: *** No rule to make target `install'.  Stop.```

**Comment by izaid** [comment]
For dynd-python, use setup.py as normal -- e.g. sudo python setup.py install

**Comment by michaelpacer** [comment]
Ah — didn't even need the `sudo`. Ok, that's actually an error then in https://github.com/libdynd/dynd-python/blob/master/BUILD_INSTALL.md#step-by-step-build-and-install part 5. I'll edit that.

**Comment by cpcloud** [comment]
if you're in a virtualenv you don't need sudo for anything -- sudo install anything is generally a bad idea.

**Comment by michaelpacer** [comment]
Even for the C++ package?

**Comment by cpcloud** [comment]
hmm yeah was just about to follow up and say you'll probably need it for that :P

**Comment by michaelpacer** [comment]
Ok so this is a much stranger error: 

```
python -c 'from dynd import nd; print(nd.array("success!"))'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/cocosci/Dropbox/Work/Resources/Repos/dynd-python/dynd/__init__.py", line 2, in <module>
    from .config import _dynd_version_string as __libdynd_version__, \
ImportError: No module named 'dynd.config'
```

This is after successfully running `python setup.py install`.

**Comment by cpcloud** [comment]
you need to run the `export LD_LIBRARY_PATH` that i show above

**Comment by michaelpacer** [comment]
So when I try `export LD_LIBRARY_PATH=~/.virtualenvs/dynd/lib:${LD_LIBRARY_PATH}` it still doesn't work.

**Comment by michaelpacer** [comment]
oh, `cd` fixes it. What is that doing? I didn't think `cd` without arguments did anything?

**Comment by michaelpacer** [comment]
Also — :+1:!

**Comment by insertinterestingnamehere** [comment]
Glad to see you got it working!

**Comment by michaelpacer** [comment]
One more bit: when I run, 

`python -c "import dynd;dynd.test()"`

Per https://github.com/libdynd/libdynd/blob/master/docs/developer-guide.md#running-the-tests one test is skipped. I'm not sure why (I've mostly seen tests skipped on Travis builds). Just wanted to let you know.

**Comment by izaid** [comment]
That's okay, some of our tests are conditional. In that particular case, it's probably skipping a Numba interoperability test.

**Comment by michaelpacer** [comment]
@insertinterestingnamehere Yes! A bit of a slog but thanks to you @cpcloud and @izaid we're off the ground and running!
