### ISSUE TITLE
Segfault on OS X

### ISSUE THREAD

**Issue by izaid** [libdynd/dynd-python#411]
See https://travis-ci.org/libdynd/dynd-python/jobs/88211474

I don't know what happened here, but somehow one of the recent changes in libdynd (probably today) caused dynd-python to start segfaulting on OS X for Python 2 only. No one has touched DyND Python since yesterday, at which point it was working.

I'll be digging into this...

**Comment by insertinterestingnamehere** [comment]
That's odd. Here's a thought... There are a few places where, in the Python bindings, the `except +translate_exception` block is omitted. A change of behavior in libdynd must have caused a new exception that the Python bindings weren't prepared to catch.

**Comment by izaid** [comment]
Fixed.
