### ISSUE TITLE
Numba interoperability bug (Priority: High)

### ISSUE THREAD

**Issue by izaid** [libdynd/dynd-python#569]
DyND Python's Numba interoperability broke recently, due to changes from the Numba side. We need to fix this ASAP.

**Comment by seibert** [comment]
What was the change that broke DyND?

**Comment by izaid** [comment]
Pinging @insertinterestingnamehere, who mentioned this to me.

**Comment by insertinterestingnamehere** [comment]
The issue is here: https://github.com/libdynd/dynd-python/blob/master/dynd/nd/functional.pyx#L73. We use an internal mechanism there, so it's not surprising that it broke, but it's important for us to fix it now since our test suite currently crashes if a newer numba is installed.

**Comment by izaid** [comment]
Thanks, @insertinterestingnamehere. Yeah, I don't know anything more, other then it just stopped working one day. My understanding is Numba has better support for what we need now, so it's probably time to update the interoperability anyway.

**Comment by insertinterestingnamehere** [comment]
Yep. That's pretty much the extent of my knowledge as well.

**Comment by seibert** [comment]
Ah, OK.  Pinging @pitrou for suggestions on how to fix the usage.  I don't know that we have a public interface for what you are doing, so some breakage now and then is probably to be expected.

**Comment by pitrou** [comment]
Try `compile_res = func.overloads[signature]`.

**Comment by izaid** [comment]
Fixed, thanks guys!
