### ISSUE TITLE
Fix build (base_fixed_dim_type.hpp)

### ISSUE THREAD

**Issue by skrah** [libdynd/dynd-python#709]
The build seems broken with the latest libdynd:

C:\Users\stefan\dynd-python\build\temp.win-amd64-2.7\Release\dynd\ndt\type.cxx(290): fatal error C1083: Cannot open include file: 'dynd/types/base_fixed_dim_type.hpp': No such file or directory [C:\Users\stefan\dynd-python\build\temp.win-amd64-2.7\Release\dynd.ndt.type.vcxproj]

**Comment by izaid** [comment]
Yeah, the DyND Python build is currently broken. It will be that for a little bit (I think I pinged everyone on this on a PR from yesterday). I'm trying to fix some of the long-standing issues with how we dispatch. Hopefully should be back in a decent state by Monday.

**Comment by skrah** [comment]
Everything works again, thanks!
