### ISSUE TITLE
os.path.samefile not available on Windows (Python 2.7)

### ISSUE THREAD

**Issue by skrah** [libdynd/dynd-python#711]
The regular Python 2.7 distribution doesn't have ```os.path.samefile``` on Windows.  It is used here:

https://github.com/libdynd/dynd-python/blob/master/setup.py#L8

Anaconda has the method.

**Comment by insertinterestingnamehere** [comment]
Hmm. Good find. It appears that it's documented as Unix-only in Python 2 even though it is sometimes there on Windows installations. It's not immediately apparent to me why it would be missing in the official installers but present in the Anaconda python. I'll see if I can get a fix up.
