### ISSUE TITLE
How do I install DyND for use with Python?

### ISSUE THREAD

**Issue by mrocklin** [libdynd/dynd-python#737]
Is it still this as recommended by the dynd-python readme?

    conda install -c https://conda.binstar.org/mwiebe dynd-python

If so then could this be moved to a installation page on the docs?

**Comment by insertinterestingnamehere** [comment]
Good catch. For some reason I thought we had already updated that. The best way to get dynd-python is to just run `conda install dynd-python`. We have development builds too, but those are a bit unstable. I'll update the readme accordingly.

**Comment by mrocklin** [comment]
Updating the readme sounds good.  If you care about adoption then I strongly recommend putting a tiny page on libdynd.org.

**Comment by mrocklin** [comment]
Any thoughts on conda-forge?  I have found it to be stable, convenient, and well maintained

**Comment by insertinterestingnamehere** [comment]
Yes. I'll add some instructions there as well.
WRT conda-forge, it's a great system. We've tried to get libdynd up there before and got hung up on toolchain issues. Their current C++ compiler is too old to be able to build libdynd (or really any C++ 11 package). https://github.com/conda-forge/docker-images/pull/22 changes this, but it's been moving slowly.

**Comment by mrocklin** [comment]
Alrighty.  Thanks for the pointer
